version: '2.2'
services:
  web-server:
    build: .
    container_name: web-server
    ports:
     - 80:80
     - 443:443
    volumes:
      - ./www:/var/www/html
    links:
      - mysql

  mysql:
    image: mysql:5.7
    container_name: mysql
    volumes:
     - /var/lib/mysql
    ports: 
     - 3306:3306
    command: --init-file /data/application/init.sql
    volumes:
        - ./database/mysql/init.sql:/data/application/init.sql
    environment:
        MYSQL_ROOT_USER: root
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: comments
        MYSQL_USER: php
        MYSQL_PASSWORD: php

  mongodb:
    image: mongo:3
    container_name: mongodb
    volumes:
      - ./data/mongo:/data/db
    ports: 
     - 27017:27017

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2
    container_name: elasticsearch
    volumes:
      - ./data/elasticsearch:/usr/share/elasticsearch/data
    environment:
      - node.name=es01
      - cluster.name=graylog-server
      - cluster.initial_master_nodes=es01
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    ports:
     - 9200:9200

  graylog:
    image: graylog/graylog:3.0
    container_name: graylog
    volumes:
      - ./data/graylog/journal:/usr/share/graylog/data/journal
      - ./graylog/config:/usr/share/graylog/data/config
    environment:
      - GRAYLOG_PASSWORD_SECRET=fd168954-7ba0-48f9-a093-6c3796a41695
      # Password: admin
      - GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      - GRAYLOG_HTTP_EXTERNAL_URI=http://127.0.0.1:9000/
    links:
      - mongodb:mongo
      - elasticsearch
    depends_on:
      - mongodb
      - elasticsearch
    ports:
      # Graylog web interface and REST API
      - 9000:9000
      # Syslog TCP
      - 1514:1514
      # Syslog UDP
      - 1514:1514/udp
      # GELF TCP
      - 12201:12201
      # GELF UDP
      - 12201:12201/udp

  cadvisor:
    image: google/cadvisor:latest
    command: ["-logtostderr", "-docker_only", "-v=4"]
    container_name: cadvisor
    ports:
      - 8080:8080
    volumes:
      - /:/rootfs:ro 
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    ports:
      - 9100:9100

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=444e0ade-ad46-4d7e-9406-283b5564d721
    links:
      - elasticsearch:elasticsearch
      - prometheus:prometheus